"use strict";
(function(module){if(typeof define==='function'&&define.amd){define(['exports'],function(exports){module(exports);});}else if(typeof exports==='object'&&exports!==null&&typeof exports.nodeName!=='string'){module(exports);}else{module(typeof self!=='undefined'?self:this);}}(function(B){let Ew=2463534242,Do=()=>{let x=Ew;x^=x<<13;x^=x>>>17;x^=x<<5;Ew=x;return x;},E=f=>function(){return f(this);},H=f=>function(p1){return f(this,p1);},L=f=>function(p1,p2){return f(this,p1,p2);},Ba=f=>function(p1,p2,p3){return f(this,
p1,p2,p3,p3);},EK=f=>(args,callback)=>{if(!args){args=[];}let javaArgs=R(Bf(),args.length);for(let i=0;i<args.length;++i){javaArgs.data[i]=Bi(args[i]);}Hi(()=>{f.call(null,javaArgs);},callback);},Bp=target=>target.$clinit=()=>{},Hq=obj=>{let cls=obj.constructor;let arrayDegree=0;while(cls.$meta&&cls.$meta.item){++arrayDegree;cls=cls.$meta.item;}let clsName="";if(cls.$meta.primitive){clsName=cls.$meta.name;}else {clsName=cls.$meta?cls.$meta.name||"a/"+cls.name:"@"+cls.name;}while(arrayDegree-->0){clsName+="[]";}return clsName;},F
=superclass=>{if(superclass===0){return function(){};}if(superclass===void 0){superclass=Bf();}return function(){superclass.call(this);};},B4=cls=>CI(cls),Bf=()=>D,Bv=f=>function(){return f.apply(null,[this].concat(Array.prototype.slice.call(arguments)));},Ht=()=>{return {$array:null,classObject:null,$meta:{supertypes:[],superclass:null}};},Cc=(name,binaryName)=>{let cls=Ht();cls.$meta.primitive=true;cls.$meta.name=name;cls.$meta.binaryName=binaryName;cls.$meta.enum=false;cls.$meta.item=null;cls.$meta.simpleName
=null;cls.$meta.declaringClass=null;cls.$meta.enclosingClass=null;return cls;},CQ=Cc("char","C"),BG=Cc("int","I"),ER=Cc("void","V");
if(typeof BigInt!=='function'){}else if(typeof BigInt64Array!=='function'){}else {}let G9=Math.imul||function(a,b){let ah=a>>>16&0xFFFF;let al=a&0xFFFF;let bh=b>>>16&0xFFFF;let bl=b&0xFFFF;return al*bl+(ah*bl+al*bh<<16>>>0)|0;},R=(cls,sz)=>{let data=new Array(sz);data.fill(null);return new (X(cls))(data);},U=(cls,data)=>new (X(cls))(data),Hz=(cls,sz)=>new (X(cls))(new Array(sz));
if(typeof BigInt64Array!=='function'){}else {}let B0=sz=>new FK(new Uint16Array(sz)),BZ=sz=>new DM(new Int32Array(sz)),M=data=>{let buffer=new Int32Array(data.length);buffer.set(data);return new DM(buffer);},X=cls=>{let result=cls.$array;if(result===null){function JavaArray(data){(Bf()).call(this);this.data=data;}JavaArray.prototype=Object.create((Bf()).prototype);JavaArray.prototype.type=cls;JavaArray.prototype.constructor=JavaArray;JavaArray.prototype.toString=function(){let str="[";for(let i=0;i<this.data.length;++i)
{if(i>0){str+=", ";}str+=this.data[i].toString();}str+="]";return str;};JavaArray.prototype.q=function(){let dataCopy;if('slice' in this.data){dataCopy=this.data.slice();}else {dataCopy=new this.data.constructor(this.data.length);for(let i=0;i<dataCopy.length;++i){dataCopy[i]=this.data[i];}}return new (X(this.type))(dataCopy);};let name="["+cls.$meta.binaryName;JavaArray.$meta={item:cls,supertypes:[Bf()],primitive:false,superclass:Bf(),name:name,binaryName:name,enum:false,simpleName:null,declaringClass:null,
enclosingClass:null};JavaArray.classObject=null;JavaArray.$array=null;result=JavaArray;cls.$array=JavaArray;}return result;},Ev=(cls,dimensions)=>{let first=0;for(let i=dimensions.length -1;i>=0;i=i -1|0){if(dimensions[i]===0){first=i;break;}}if(first>0){for(let i=0;i<first;i=i+1|0){cls=X(cls);}if(first===dimensions.length -1){return R(cls,dimensions[first]);}}let arrays=new Array(HE(dimensions,first));let firstDim=dimensions[first]|0;for(let i=0;i<arrays.length;i=i+1|0){arrays[i]=R(cls,firstDim);}return Gd(cls,
arrays,dimensions,first);},HE=(dimensions,start)=>{let val=dimensions[start+1]|0;for(let i=start+2;i<dimensions.length;i=i+1|0){val=val*(dimensions[i]|0)|0;if(val===0){break;}}return val;},Gd=(cls,arrays,dimensions,start)=>{let limit=arrays.length;for(let i=start+1|0;i<dimensions.length;i=i+1|0){cls=X(cls);let dim=dimensions[i];let index=0;let packedIndex=0;while(index<limit){let arr=Hz(cls,dim);for(let j=0;j<dim;j=j+1|0){arr.data[j]=arrays[index];index=index+1|0;}arrays[packedIndex]=arr;packedIndex=packedIndex
+1|0;}limit=packedIndex;}return arrays[0];},Cl,FC=strings=>{F8();Cl=new Array(strings.length);for(let i=0;i<strings.length;++i){Cl[i]=Dw(Bi(strings[i]));}},G=index=>Cl[index],Eq=(array,offset,count)=>{let result="";let limit=offset+count;for(let i=offset;i<limit;i=i+1024|0){let next=Math.min(limit,i+1024|0);result+=String.fromCharCode.apply(null,array.subarray(i,next));}return result;},Bi=str=>str===null?null:E9(str),CG=str=>str===null?null:str.cL,F8=()=>Bq(),Dw;
{Dw=str=>str;}let Ga=(obj,cls)=>obj instanceof Bf()&&!!obj.constructor.$meta&&B9(obj.constructor,cls),B9=(from,to)=>{if(from===to){return true;}let map=from.$meta.assignableCache;if(typeof map==='undefined'){map=new Map();from.$meta.assignableCache=map;}let cachedResult=map.get(to);if(typeof cachedResult!=='undefined'){return cachedResult;}if(to.$meta.item!==null){let result=from.$meta.item!==null&&B9(from.$meta.item,to.$meta.item);map.set(to,result);return result;}let supertypes=from.$meta.supertypes;for(let i
=0;i<supertypes.length;i=i+1|0){if(B9(supertypes[i],to)){map.set(to,true);return true;}}map.set(to,false);return false;},S=ex=>{throw F9(ex);},Bx=Symbol("javaException"),F9=ex=>{let err=ex.$jsException;if(!err){let javaCause=HH(ex);let jsCause=javaCause!==null?javaCause.$jsException:void 0;let cause=typeof jsCause==="object"?{cause:jsCause}:void 0;err=new Bh("Java exception thrown",cause);if(typeof Error.captureStackTrace==="function"){Error.captureStackTrace(err);}err[Bx]=ex;ex.$jsException=err;Ei(err,ex);}return err;},Ei
=(err,ex)=>{if(typeof E7==="function"&&err.stack){let stack=E7(err.stack);let javaStack=R(Fq(),stack.length);let elem;let noStack=false;for(let i=0;i<stack.length;++i){let element=stack[i];elem=FI(Bi(element.className),Bi(element.methodName),Bi(element.fileName),element.lineNumber);if(elem==null){noStack=true;break;}javaStack.data[i]=elem;}if(!noStack){F2(ex,javaStack);}}},Bh;
if(typeof Reflect==='object'){let defaultMessage=Symbol("defaultMessage");Bh=function Bh(message,cause){let self=Reflect.construct(Error,[void 0,cause],Bh);Object.setPrototypeOf(self,Bh.prototype);self[defaultMessage]=message;return self;}
;Bh.prototype=Object.create(Error.prototype,{constructor:{configurable:true,writable:true,value:Bh},message:{get(){try {let javaException=this[Bx];if(typeof javaException==='object'){let javaMessage=EH(javaException);if(typeof javaMessage==="object"){return javaMessage!==null?javaMessage.toString():null;}}return this[defaultMessage];}catch(e){return "Exception occurred trying to extract Java exception message: "+e;}}}});}else {Bh=Error;}let ET=e=>e instanceof Error&&typeof e[Bx]==='object'?e[Bx]:null,Gw=err=>
{let ex=err[Bx];if(!ex){ex=E3(Bi("(JavaScript) "+err.toString()));err[Bx]=ex;ex.$jsException=err;Ei(err,ex);}return ex;},E3=message=>G$(message),EH=t=>Ex(t),HH=t=>EA(t),Fq=()=>H5,FI=(className,methodName,fileName,lineNumber)=>{{return null;}},F2=(e,stack)=>{},C_=null,Ge=data=>{let i=0;let packages=new Array(data.length);for(let j=0;j<data.length;++j){let prefixIndex=data[i++];let prefix=prefixIndex>=0?packages[prefixIndex]:"";packages[j]=prefix+data[i++]+".";}C_=packages;},Dg=data=>{let packages=C_;let i=0;while
(i<data.length){let cls=data[i++];cls.$meta={};let m=cls.$meta;let className=data[i++];m.name=className!==0?className:null;if(m.name!==null){let packageIndex=data[i++];if(packageIndex>=0){m.name=packages[packageIndex]+m.name;}}m.binaryName="L"+m.name+";";let superclass=data[i++];m.superclass=superclass!==0?superclass:null;m.supertypes=data[i++];if(m.superclass){m.supertypes.push(m.superclass);cls.prototype=Object.create(m.superclass.prototype);}else {cls.prototype={};}let flags=data[i++];m.enum=(flags&8)!==
0;m.flags=flags;m.primitive=false;m.item=null;cls.prototype.constructor=cls;cls.classObject=null;m.accessLevel=data[i++];let innerClassInfo=data[i++];if(innerClassInfo===0){m.simpleName=null;m.declaringClass=null;m.enclosingClass=null;}else {let enclosingClass=innerClassInfo[0];m.enclosingClass=enclosingClass!==0?enclosingClass:null;let declaringClass=innerClassInfo[1];m.declaringClass=declaringClass!==0?declaringClass:null;let simpleName=innerClassInfo[2];m.simpleName=simpleName!==0?simpleName:null;}let clinit
=data[i++];cls.$clinit=clinit!==0?clinit:function(){};let virtualMethods=data[i++];if(virtualMethods!==0){for(let j=0;j<virtualMethods.length;j+=2){let name=virtualMethods[j];let func=virtualMethods[j+1];if(typeof name==='string'){name=[name];}for(let k=0;k<name.length;++k){cls.prototype[name[k]]=func;}}}cls.$array=null;}},Hi=(runner,callback)=>{let result;try {result=runner();}catch(e){result=e;}if(typeof callback!=='undefined'){callback(result);}else if(result instanceof Error){throw result;}};
function D(){this.$id$=0;}
let K=a=>{return;},H4=()=>{let a=new D();K(a);return a;},CY=a=>{return CI(a.constructor);},Fd=(a,b)=>{return a!==b?0:1;},DJ=a=>{let b,c;b=Hd(Dd(a));c=BY();Bd(Bd(c,G(0)),b);return BC(c);},Dd=a=>{let b;b=a;if(!b.$id$)b.$id$=Do();return a.$id$;},Eo=a=>{let b,c,d;if(!Ga(a,Bz)){b=a;if(b.constructor.$meta.item===null)S(Gg());}c=Fh(a);b=c;d=Do();b.$id$=d;return c;};
function Bg(){let a=this;D.call(a);a.c$=null;a.c9=null;a.c5=0;a.c_=0;}
let En=a=>{a.c5=1;a.c_=1;a.h();},HT=()=>{let a=new Bg();En(a);return a;},DF=(a,b)=>{a.c5=1;a.c_=1;a.h();a.c$=b;},H3=a=>{let b=new Bg();DF(b,a);return b;},Em=(a,b,c)=>{a.c5=1;a.c_=1;a.h();a.c$=b;a.c9=c;},HQ=(a,b)=>{let c=new Bg();Em(c,a,b);return c;},FZ=a=>{return a;},Ex=a=>{return a.c$;},EA=a=>{return a.c9===a?null:a.c9;},Bk=F(Bg),BU=a=>{En(a);},HP=()=>{let a=new Bk();BU(a);return a;},Ci=(a,b)=>{DF(a,b);},H1=a=>{let b=new Bk();Ci(b,a);return b;},N=F(Bk),Bl=a=>{BU(a);},HR=()=>{let a=new N();Bl(a);return a;},B$
=(a,b)=>{Ci(a,b);},G$=a=>{let b=new N();B$(b,a);return b;},BV=F(N),Ct=a=>{Bl(a);},Eu=()=>{let a=new BV();Ct(a);return a;},Cx=F(N),B6=(a,b)=>{B$(a,b);},HZ=a=>{let b=new Cx();B6(b,a);return b;},HL=F(),Hj=(b,c)=>{let d,e,f,g;d=b.data;e=B0(c);f=Eb(c,d.length);g=0;while(g<f){e.data[g]=d[g];g=g+1|0;}return e;},Fo=(b,c)=>{let d,e,f,g;d=b.data;e=F$(Dh(CY(b)),c);f=Eb(c,d.length);g=0;while(g<f){e.data[g]=d[g];g=g+1|0;}return e;},F_=(b,c,d,e)=>{let f,g;if(c>d)S(BS());while(c<d){f=b.data;g=c+1|0;f[c]=e;c=g;}},Gv=F(),F$
=(b,c)=>{if(b===null)S(Fu());if(b===B4(ER))S(BS());if(c<0)S(EN());return E_(CV(b),c);},E_=(b,c)=>{if(b.$meta.primitive){switch(b){};}return R(b,c);},Bz=F(0);
function P(){let a=this;D.call(a);a.cI=null;a.cH=0;a.cG=0;}
let Bn=(a,b,c,d)=>{K(a);a.cI=b;a.cH=c;a.cG=d;},G6=a=>{return a.cI;},FN=a=>{return I(a.cH,a.cG);},HG=a=>{let b,c,$$je;a:{try{b=Eo(a);}catch($$e){$$je=Gw($$e);if($$je instanceof Ca){c=$$je;break a;}else{throw $$e;}}return b;}S(FT(G(1),c));};
function BA(){P.call(this);this.c4=0;}
let Er=(a,b,c,d)=>{Bn(a,b,c,d);a.c4=0;},Dt=(a,b,c)=>{let d=new BA();Er(d,a,b,c);return d;},Ho=a=>{return a.c4;},FR=(a,b)=>{a.c4=b;},Gb=(a,b)=>{let c,d,e,f,g,h,i,j;c=Bb();d=BZ(2);e=d.data;e[0]=(-1);e[1]=1;f=e.length;g=0;while(g<f){h=e[g];i=a.cG+h|0;a:{while(true){if(!b.t(a.cH,i))break a;if(b.u(a.cH,i)!==null)break;c.v(I(a.cH,i));i=i+h|0;}if((b.u(a.cH,i)).w()!==a.cI)c.v(I(a.cH,i));}g=g+1|0;}g=0;while(g<f){h=e[g];j=a.cH+h|0;b:{while(true){if(!b.t(j,a.cG))break b;if(b.u(j,a.cG)!==null)break;c.v(I(j,a.cG));j=j+h
|0;}if((b.u(j,a.cG)).w()!==a.cI)c.v(I(j,a.cG));}g=g+1|0;}return c;},HO=a=>{Bc();return CN;},E5=F(),BP=(b,c)=>{let d,e,f,g,h,i;d=b.x(c);if(d===null){e=new Cx;f=BJ(c);g=BY();Bd(Bd(g,G(2)),f);B6(e,BC(g));S(e);}e=(b.z(D4(c))).B();while(e.C()){h=e.D();i=!(h instanceof Bj)?h.E(b):h.F(b);if(i.G(d))return 1;}return 0;},GV=(b,c)=>{if(!BP(b,c))return 0;return Dr(b,c)?0:1;},Gs=(b,c)=>{if(BP(b,c))return 0;return Dr(b,c)?0:1;},G_=(b,c)=>{let d,e,f,g,h;d=b.x(c);e=Bb();f=(b.z(D4(c))).B();while(f.C()){g=f.D();h=g.E(b);if(h.G(d))e.v(g.J());}return e;},Dr
=(b,c)=>{let d,e,f,g,h;d=(b.z(c)).B();while(d.C()){e=d.D();f=(e.E(b)).B();while(f.C()){g=f.D();h=b.K();h.L(e.J(),g);if(!BP(h,c))return 1;}}return 0;},D4=b=>{Y();return b!==O?O:Be;},DS=F(0),B7=F(0),B8=F(),EF=a=>{K(a);},Fy=(a,b)=>{let c,d;c=a.B();while(c.C()){d=c.D();if(HN(d,b))return 1;}return 0;},EO=(a,b)=>{let c,d;c=0;d=b.B();while(d.C()){if(!a.v(d.D()))continue;c=1;}return c;},Ee=F(0),DA=F(0);
function Cb(){B8.call(this);this.cS=0;}
let Dv=a=>{EF(a);},FA=a=>{return Hl(a);},Bm=F(0),CD=F(),BD=F(0),Dx=F(CD),FF=null,B3=()=>{B3=Bp(Dx);Fg();},Hd=b=>{B3();return Fk(b,4);},HB=b=>{let c,d,e;B3();if(!b)return 32;c=0;d=b>>>16|0;if(d)c=16;else d=b;e=d>>>8|0;if(!e)e=d;else c=c|8;d=e>>>4|0;if(!d)d=e;else c=c|4;e=d>>>2|0;if(!e)e=d;else c=c|2;if(e>>>1|0)c=c|1;return (32-c|0)-1|0;},Fg=()=>{FF=B4(BG);},Ca=F(Bk),Du=a=>{BU(a);},Gg=()=>{let a=new Ca();Du(a);return a;},Di=F(N),D2=a=>{Bl(a);},Fu=()=>{let a=new Di();D2(a);return a;},Br=F(0),Dq=F(0),Cz=F(),CO=
a=>{K(a);},GD=()=>{let a=new Cz();CO(a);return a;},FH=a=>{GS();},Gl=b=>{b.Q();},Cr=F(),FE=null,F0=null,Cn=()=>{Cn=Bp(Cr);GM();},GI=(b,c)=>{Cn();if(c>=2&&c<=36&&b>=0&&b<c)return b<10?(48+b|0)&65535:((97+b|0)-10|0)&65535;return 0;},GM=()=>{FE=B4(CQ);F0=R(Cr,128);};
function BH(){let a=this;D.call(a);a.db=null;a.dj=0;}
let CM=(a,b,c)=>{K(a);a.db=b;a.dj=c;},Hx=a=>{return a.db.f();},HF=F(),Fk=(b,c)=>{let d,e,f,g,h,i,j,k;if(!b)return G(3);d=1<<c;e=d-1|0;f=(((32-HB(b)|0)+c|0)-1|0)/c|0;g=B0(f);h=G9(f-1|0,c);i=0;while(h>=0){j=g.data;k=i+1|0;j[i]=GI((b>>>h|0)&e,d);h=h-c|0;i=k;}return E1(g);},EG=F(P),D_=(a,b,c,d)=>{Bn(a,b,c,d);},Eg=(a,b,c)=>{let d=new EG();D_(d,a,b,c);return d;},Fn=(a,b)=>{let c,d,e,f,g,h,i,j,k,l;c=Bb();d=R(X(BG),8);e=d.data;e[0]=M([(-2),(-1)]);e[1]=M([(-2),1]);e[2]=M([(-1),(-2)]);e[3]=M([(-1),2]);e[4]=M([1,(-2)]);e[5]
=M([1,2]);e[6]=M([2,(-1)]);e[7]=M([2,1]);f=e.length;g=0;while(g<f){h=e[g];i=h.data;j=a.cH+i[0]|0;k=a.cG+i[1]|0;if(b.t(j,k)){l=b.u(j,k);if(!(l!==null&&l.w()===a.cI))c.v(I(j,k));}g=g+1|0;}return c;},Gf=a=>{Bc();return CE;},DB=F(0),E6=F(),Eb=(b,c)=>{if(b<c)c=b;return c;},BQ=(b,c)=>{if(b>c)c=b;return c;},BM=b=>{if(b<0)b= -b|0;return b;},HI=F(),Eh=F(),Bw=null,V=null,T=null,BF=null,Q=null,BR=null,W=()=>{W=Bp(Eh);FB();},Fb=b=>{let c;W();c=window.document;Bw=c.getElementById("chess");V=Bw.getContext("2d");T=GF();GJ();},GJ
=()=>{let b,c,d,e,f,g,h,i,j,k,l,m;W();b=R(X(J),13);c=b.data;c[0]=U(J,[G(4),G(5)]);c[1]=U(J,[G(6),G(7)]);c[2]=U(J,[G(8),G(9)]);c[3]=U(J,[G(10),G(11)]);c[4]=U(J,[G(12),G(13)]);c[5]=U(J,[G(14),G(15)]);c[6]=U(J,[G(16),G(17)]);c[7]=U(J,[G(18),G(19)]);c[8]=U(J,[G(20),G(21)]);c[9]=U(J,[G(22),G(23)]);c[10]=U(J,[G(24),G(25)]);c[11]=U(J,[G(26),G(27)]);c[12]=U(J,[G(28),G(29)]);d=c.length;e=BZ(1);e.data[0]=0;f=0;while(f<d){g=c[f];h=g.data;i=h[0];j=h[1];k=window.document.createElement("img");l=CG(j);k.src=l;m=Hg(e,d);k.addEventListener("load",
Bu(Z(m),"handleEvent"),!!0);BF.Y(i,CU(k));f=f+1|0;}},FW=()=>{let b,c;W();B1();b=Bw;c=HK();b.addEventListener("mousedown",Bu(Z(c),"handleEvent"),!!0);b=Bw;c=GZ();b.addEventListener("mouseup",Bu(Z(c),"handleEvent"),!!0);},B1=()=>{let b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s;W();V.clearRect(0.0,0.0,640.0,640.0);b=Z(BF.bb(G(4)));V.drawImage(b,0.0,0.0,640.0,640.0);c=0;while(c<8){d=0;while(d<8){a:{if(Q!==null){e=Q;if(e.bc()==c){e=Q;if(e.bd()==d)break a;}}f=(T.be()).u(c,d);if(f!==null){e=BJ(f.w());g=BJ(f.bf());h=BY();Bd(Cj(Bd(h,
e),95),g);i=BC(h);j=Z(BF.bb(i));e=V;k=d*80|0;l=c*80|0;e.drawImage(j,k,l,80.0,80.0);}}d=d+1|0;}c=c+1|0;}e=V;g="rgba(0,255,0,0.5)";e.fillStyle=g;e=BR.B();while(e.C()){m=e.D();n=(m.bd()*80|0)+40.0;o=(m.bc()*80|0)+40.0;V.beginPath();V.arc(n,o,10.0,0.0,6.283185307179586);V.fill();}if(Q!==null){e=T.be();g=Q;p=g.bc();g=Q;q=g.bd();f=e.u(p,q);if(f!==null){e=BJ(f.w());g=BJ(f.bf());h=BY();Bd(Cj(Bd(h,e),95),g);i=BC(h);j=Z(BF.bb(i));r=Q.bd()*80|0;s=Q.bc()*80|0;V.globalAlpha=0.6;V.drawImage(j,r,s,80.0,80.0);V.globalAlpha
=1.0;}}},DC=(b,c)=>{let d,e,f,g;W();d=Bw.getBoundingClientRect().left;e=Bw.getBoundingClientRect().top;f=(b-d)/80.0|0;g=(c-e)/80.0|0;if(g>=0&&g<8&&f>=0&&f<8)return I(g,f);return null;},GT=b=>{let c,d,e,f,g;W();c=V;d="rgba(255,0,0,0.5)";c.fillStyle=d;c=b.B();while(c.C()){e=c.D();d=V;f=e.bd()*80|0;g=e.bc()*80|0;d.fillRect(f,g,80.0,80.0);}c=GD();setTimeout(Bu(Z(c),"onTimer"),500);},GS=()=>{W();B1();},E$=b=>{let c,d,e,f,g,h,i,j,k;W();if(Q!==null){c=b.clientX;d=b.clientY;e=DC(c,d);if(e!==null){f=T.bi(Q,e);if(!f)
{g=(T.be()).K();g.L(Q,e);h=T;h=h.bj();i=G_(g,h);GT(i);}else{h=T.be();j=h.u(e.bc(),e.bd());if(j instanceof Bt&&!(e.bc()&&e.bc()!=7)){k=Bi(prompt("Promotion (Queen,Rook,Bishop,Knight)","Queen"));if(k!==null)T.bm(e,k);}}}Q=null;BR.bn();if(T.bo())alert("Échec et mat !");else if(T.bp())alert("Pat !");B1();}},Hb=b=>{let c,d,e;W();c=DC(b.clientX,b.clientY);if(c!==null){d=T.be();e=d.u(c.bc(),c.bd());if(e!==null&&e.w()===T.bj()){Q=c;BR=e.E(T.be());B1();}}},Ha=(b,c,d)=>{let e;W();e=b.data;e[0]=e[0]+1|0;if(e[0]==c)FW();},FB
=()=>{BF=HC();Q=null;BR=Bb();},GW=F(),Bu=(b,c)=>{let name='jso$functor$'+c;let result=b[name];if(typeof result!=='function'){let fn=function(){return b[c].apply(b,arguments);};result=()=>fn;b[name]=result;}return result();},Ch=F(0),DG=F(BV),DQ=a=>{Ct(a);},D5=()=>{let a=new DG();DQ(a);return a;},BT=F(0);
function CA(){let a=this;D.call(a);a.df=null;a.dg=0;}
let DP=(a,b,c)=>{K(a);a.df=b;a.dg=c;},Hg=(a,b)=>{let c=new CA();DP(c,a,b);return c;},EU=(a,b)=>{Ec(a,b);},Ec=(a,b)=>{Ha(a.df,a.dg,b);},F1=(b,c)=>{b.bt(c);},Gm=F(),HN=(b,c)=>{if(b===c)return 1;return b!==null?b.bu(c):c!==null?0:1;},GR=(b,c,d)=>{if(b>=0&&c>=0&&c<=(d-b|0))return b;S(Eu());},Fv=F(),CW=F(0);
function BX(){let a=this;D.call(a);a.da=null;a.cZ=null;}
let CJ=(a,b,c)=>{K(a);a.da=b;a.cZ=c;},HY=(a,b)=>{let c=new BX();CJ(c,a,b);return c;};
function Cs(){let a=this;BX.call(a);a.c8=0;a.cW=null;}
let Dz=(a,b,c)=>{CJ(a,b,null);a.c8=c;},Ff=(a,b)=>{let c=new Cs();Dz(c,a,b);return c;},C7=F(0),Ez=F(),Fp=null,C1=null,B2=null,BL=null,DU=null,CZ=null,Da=null,BB=()=>{BB=Bp(Ez);EX();},Hr=b=>{let c,d;BB();c=BL;d=Z(b);c.delete(d);},GK=b=>{let c,d;BB();c=B2;d=Z(b);c.delete(d);},EX=()=>{let b;Fp=new WeakMap();b=!(typeof WeakRef!=='undefined'?1:0)?null:new WeakMap();C1=b;b=!(typeof WeakRef!=='undefined'?1:0)?null:new Map();B2=b;b=!(typeof WeakRef!=='undefined'?1:0)?null:new Map();BL=b;if(B2===null)b=null;else{b=FU();b
=new FinalizationRegistry(Bu(Z(b),"accept"));}CZ=b;if(BL===null)b=null;else{b=F7();b=new FinalizationRegistry(Bu(Z(b),"accept"));}Da=b;};
function BI(){let a=this;D.call(a);a.cJ=null;a.cM=0;}
let Ce=a=>{CC(a,16);},HX=()=>{let a=new BI();Ce(a);return a;},CC=(a,b)=>{K(a);a.cJ=B0(b);},HS=a=>{let b=new BI();CC(b,a);return b;},Dn=(a,b)=>{return a.bx(a.cM,b);},CS=(a,b,c)=>{let d,e,f;if(b>=0&&b<=a.cM){if(c===null)c=G(30);else if(c.by())return a;a.bz(a.cM+c.bA()|0);d=a.cM-1|0;while(d>=b){a.cJ.data[d+c.bA()|0]=a.cJ.data[d];d=d+(-1)|0;}a.cM=a.cM+c.bA()|0;d=0;while(d<c.bA()){e=a.cJ.data;f=b+1|0;e[b]=c.bB(d);d=d+1|0;b=f;}return a;}S(D5());},DZ=(a,b)=>{return a.bC(a.cM,b);},DD=(a,b,c)=>{GX(a,b,b+1|0);a.cJ.data[b]
=c;return a;},Dy=(a,b,c)=>{return a.bE(b,c===null?G(30):c.f());},C2=(a,b)=>{let c;if(a.cJ.data.length>=b)return;c=a.cJ.data.length>=1073741823?2147483647:BQ(b,BQ(a.cJ.data.length*2|0,5));a.cJ=Hj(a.cJ,c);},DO=a=>{return Gi(a.cJ,0,a.cM);},GX=(a,b,c)=>{let d,e;d=a.cM-b|0;a.bz((a.cM+c|0)-b|0);e=d-1|0;while(e>=0){a.cJ.data[c+e|0]=a.cJ.data[b+e|0];e=e+(-1)|0;}a.cM=a.cM+(c-b|0)|0;},ED=F(0),Dl=F(BI),DI=a=>{Ce(a);},BY=()=>{let a=new Dl();DI(a);return a;},Bd=(a,b)=>{Dn(a,b);return a;},Cj=(a,b)=>{DZ(a,b);return a;},Gz
=(a,b,c)=>{Dy(a,b,c);return a;},He=(a,b,c)=>{DD(a,b,c);return a;},GN=(a,b,c)=>{CS(a,b,c);return a;},BC=a=>{return DO(a);},G5=(a,b)=>{C2(a,b);},FM=(a,b,c)=>{return a.bK(b,c);},EV=(a,b,c)=>{return a.bL(b,c);},Hp=(a,b,c)=>{return a.bM(b,c);},Ea=F(N),Ef=a=>{Bl(a);},Fz=()=>{let a=new Ea();Ef(a);return a;},DR=F(0),C0=F(P),D9=(a,b,c,d)=>{Bn(a,b,c,d);},D0=(a,b,c)=>{let d=new C0();D9(d,a,b,c);return d;},E4=(a,b)=>{let c,d,e,f,g,h,i,j,k,l;c=Bb();d=R(X(BG),4);e=d.data;e[0]=M([(-1),(-1)]);e[1]=M([(-1),1]);e[2]=M([1,(-1)]);e[3]
=M([1,1]);f=e.length;g=0;while(g<f){h=e[g];i=h.data;j=a.cH+i[0]|0;k=a.cG+i[1]|0;a:{while(true){if(!b.t(j,k))break a;l=b.u(j,k);if(l!==null)break;c.v(I(j,k));j=j+i[0]|0;k=k+i[1]|0;}if(l.w()!==a.cI)c.v(I(j,k));}g=g+1|0;}return c;},Hh=a=>{Bc();return Cy;},CH=F(0),BN=F(BH),O=null,Be=null,Hf=null,Y=()=>{Y=Bp(BN);G8();},Gh=(a,b,c)=>{Y();CM(a,b,c);},D8=(a,b)=>{let c=new BN();Gh(c,a,b);return c;},Fl=()=>{let b,c;Y();b=R(BN,2);c=b.data;c[0]=O;c[1]=Be;return b;},G8=()=>{O=D8(G(31),0);Be=D8(G(32),1);Hf=Fl();},BO=F(Bg),Cm
=(a,b,c)=>{Em(a,b,c);},HV=(a,b)=>{let c=new BO();Cm(c,a,b);return c;},Cw=F(),CR=a=>{K(a);};
function BW(){let a=this;Cw.call(a);a.cV=0;a.cK=null;a.cY=0;a.dh=0.0;a.c6=0;}
let Hk=(a,b)=>{return R(Cs,b);},C3=a=>{B_(a,16);},HC=()=>{let a=new BW();C3(a);return a;},B_=(a,b)=>{Ck(a,b,0.75);},HU=a=>{let b=new BW();B_(b,a);return b;},Db=b=>{let c,d;if(b>=1073741824)return 1073741824;if(!b)return 16;c=b-1|0;d=c|c>>1;d=d|d>>2;d=d|d>>4;d=d|d>>8;d=d|d>>16;return d+1|0;},Ck=(a,b,c)=>{let d;CR(a);if(b>=0&&c>0.0){d=Db(b);a.cV=0;a.cK=a.bR(d);a.dh=c;DY(a);return;}S(BS());},H2=(a,b)=>{let c=new BW();Ck(c,a,b);return c;},DY=a=>{a.c6=a.cK.data.length*a.dh|0;},Hu=(a,b)=>{let c;c=D6(a,b);if(c===null)return null;return c.cZ;},D6
=(a,b)=>{let c,d,e;if(b===null)c=CL(a);else{d=b.bV();e=d&(a.cK.data.length-1|0);c=Cv(a,b,e,d);}return c;},Cv=(a,b,c,d)=>{let e;e=a.cK.data[c];while(e!==null&&!(e.c8==d&&Hw(b,e.da))){e=e.cW;}return e;},CL=a=>{let b;b=a.cK.data[0];while(b!==null&&b.da!==null){b=b.cW;}return b;},Gr=(a,b,c)=>{return G3(a,b,c);},G3=(a,b,c)=>{let d,e,f,g,h;if(b===null){d=CL(a);if(d===null){a.cY=a.cY+1|0;d=DN(a,null,0,0);e=a.cV+1|0;a.cV=e;if(e>a.c6)a.b0();}}else{f=b.bV();g=f&(a.cK.data.length-1|0);d=Cv(a,b,g,f);if(d===null){a.cY=a.cY
+1|0;d=DN(a,b,g,f);e=a.cV+1|0;a.cV=e;if(e>a.c6)a.b0();}}h=d.cZ;d.cZ=c;return h;},DN=(a,b,c,d)=>{let e;e=Ff(b,d);e.cW=a.cK.data[c];a.cK.data[c]=e;return e;},GP=(a,b)=>{let c,d,e,f,g,h,i;c=Db(!b?1:b<<1);d=a.bR(c);e=0;while(e<a.cK.data.length){f=a.cK.data[e];a.cK.data[e]=null;while(f!==null){g=d.data;h=f.c8&(c-1|0);i=f.cW;f.cW=g[h];g[h]=f;f=i;}e=e+1|0;}a.cK=d;DY(a);},GH=a=>{a.b2(a.cK.data.length);},Hw=(b,c)=>{return b!==c&&!b.bu(c)?0:1;},BK=F(BH),CF=null,Cq=null,CN=null,Cy=null,CE=null,CB=null,EL=null,Bc=()=>{Bc
=Bp(BK);FY();},Go=(a,b,c)=>{Bc();CM(a,b,c);},By=(a,b)=>{let c=new BK();Go(c,a,b);return c;},EM=()=>{let b,c;Bc();b=R(BK,6);c=b.data;c[0]=CF;c[1]=Cq;c[2]=CN;c[3]=Cy;c[4]=CE;c[5]=CB;return b;},FY=()=>{CF=By(G(33),0);Cq=By(G(34),1);CN=By(G(35),2);Cy=By(G(36),3);CE=By(G(37),4);CB=By(G(38),5);EL=EM();},C8=F(BO),EB=(a,b,c)=>{Cm(a,b,c);},FT=(a,b)=>{let c=new C8();EB(c,a,b);return c;},F6=F(N);
function CK(){D.call(this);this.dd=null;}
let Fw=(a,b)=>{K(a);a.dd=b;},BE=a=>{let b=new CK();Fw(b,a);return b;},CU=b=>{let c,d,e,f,g,h,i,j,k,l,m,n,o;if(b===null)return null;c=Bi(typeof b);d=!c.bu(G(39))&&!c.bu(G(40))?0:1;BB();e=C1;if(e!==null){if(d){f=e.get(b);g=(typeof f=='undefined'?1:0)?void 0:f.deref();if(!(typeof g=='undefined'?1:0))return g;h=BE(b);e.set(b,new WeakRef(h));return h;}if(c.bu(G(41))){i=b;j=B2;k=CZ;f=j.get(i);g=(typeof f=='undefined'?1:0)?void 0:f.deref();if(!(typeof g=='undefined'?1:0))return g;h=BE(b);l=h;j.set(i,new WeakRef(l));Es(k,
l,i);return h;}if(c.bu(G(42))){m=b;n=BL;o=Da;f=n.get(m);g=(typeof f=='undefined'?1:0)?void 0:f.deref();if(!(typeof g=='undefined'?1:0))return g;h=BE(b);l=h;n.set(m,new WeakRef(l));Es(o,l,m);return h;}if(c.bu(G(43))){f=DU;g=f===null?void 0:f.deref();if(!(typeof g=='undefined'?1:0))return g;h=BE(b);l=h;DU=new WeakRef(l);return h;}}return BE(b);},Z=b=>{if(b===null)return null;return !(b instanceof CK)?b:b.dd;},Dj=b=>{if(b===null)return null;return b instanceof Bf()?b:CU(b);},Es=(b,c,d)=>{return b.register(c,d);};
function Bj(){P.call(this);this.c1=0;}
let Ek=(a,b,c,d)=>{Bn(a,b,c,d);a.c1=0;a.c1=0;},Fx=(a,b,c)=>{let d=new Bj();Ek(d,a,b,c);return d;},Fi=(a,b)=>{a.c1=b;},HJ=(a,b)=>{let c;c=Bb();c.b6(a.F(b));if(!a.c1){if(EZ(a,b))c.v(I(a.cH,a.cG+2|0));if(Fc(a,b))c.v(I(a.cH,a.cG-2|0));}return c;},Gu=(a,b)=>{let c,d,e,f,g,h,i,j,k,l,m;c=Bb();d=BZ(3);e=d.data;e[0]=(-1);e[1]=0;e[2]=1;f=e.length;g=0;while(g<f){h=e[g];i=0;while(i<f){j=e[i];if(!(!h&&!j)){k=a.cH+h|0;l=a.cG+j|0;if(b.t(k,l)){m=b.u(k,l);if(!(m!==null&&m.w()===a.cI))c.v(I(k,l));}}i=i+1|0;}g=g+1|0;}return c;},EZ
=(a,b)=>{let c,d,e,f,g;if(b.u(a.cH,a.cG+1|0)===null&&b.u(a.cH,a.cG+2|0)===null){c=b.u(a.cH,7);if(!(c instanceof BA))return 0;d=c;if(d.b9())return 0;a:{if(!b.b$(a.cH,a.cG,Bs(a,a.cI))){e=a.cH;f=a.cG+1|0;g=a.cI;if(!b.b$(e,f,Bs(a,g))){e=a.cH;f=a.cG+2|0;g=a.cI;if(!b.b$(e,f,Bs(a,g))){e=1;break a;}}}e=0;}return e;}return 0;},Fc=(a,b)=>{let c,d,e,f,g;if(b.u(a.cH,a.cG-1|0)===null){c=a.cH;d=a.cG-2|0;if(b.u(c,d)===null){c=a.cH;d=a.cG-3|0;if(b.u(c,d)===null){e=b.u(a.cH,0);if(!(e instanceof BA))return 0;f=e;if(f.b9())return 0;a:
{if(!b.b$(a.cH,a.cG,Bs(a,a.cI))){c=a.cH;d=a.cG-1|0;g=a.cI;if(!b.b$(c,d,Bs(a,g))){c=a.cH;d=a.cG-2|0;g=a.cI;if(!b.b$(c,d,Bs(a,g))){c=1;break a;}}}c=0;}return c;}}}return 0;},Bs=(a,b)=>{Y();return b!==O?O:Be;},Hs=(a,b)=>{return a.b_(b);},Gy=a=>{Bc();return CF;},Dc=F(0);
function B5(){let a=this;Cb.call(a);a.cQ=null;a.cR=0;}
let D3=a=>{Cf(a,10);},Bb=()=>{let a=new B5();D3(a);return a;},Cf=(a,b)=>{Dv(a);if(b>=0){a.cQ=R(D,b);return;}S(BS());},HW=a=>{let b=new B5();Cf(b,a);return b;},GL=(a,b)=>{let c;if(a.cQ.data.length<b){c=a.cQ.data.length>=1073741823?2147483647:BQ(b,BQ(a.cQ.data.length*2|0,5));a.cQ=Fo(a.cQ,c);}},G2=(a,b)=>{Fs(a,b);return a.cQ.data[b];},EP=a=>{return a.cR;},EI=(a,b)=>{let c,d;a.bz(a.cR+1|0);c=a.cQ.data;d=a.cR;a.cR=d+1|0;c[d]=b;a.cS=a.cS+1|0;return 1;},EW=a=>{F_(a.cQ,0,a.cR,null);a.cR=0;a.cS=a.cS+1|0;},Fs=(a,b)=>
{if(b>=0&&b<a.cR)return;S(Eu());};
function Cu(){let a=this;D.call(a);a.c0=0;a.c3=0;}
let Dm=(a,b,c)=>{K(a);a.c0=b;a.c3=c;},I=(a,b)=>{let c=new Cu();Dm(c,a,b);return c;},Gn=a=>{return a.c0;},GG=a=>{return a.c3;},ES=(a,b)=>{let c;if(a===b)return 1;if(!(b instanceof Cu))return 0;c=b;return a.c0==c.c0&&a.c3==c.c3?1:0;},Cg=F(),CT=a=>{K(a);},HK=()=>{let a=new Cg();CT(a);return a;},G7=(a,b)=>{CP(a,b);},CP=(a,b)=>{Hb(b);},F4=(b,c)=>{b.bt(c);},Cd=F(),DW=a=>{K(a);},GZ=()=>{let a=new Cd();DW(a);return a;},GY=(a,b)=>{CX(a,b);},CX=(a,b)=>{E$(b);},Gt=(b,c)=>{b.bt(c);},FO=F(),Fh=b=>{let copy=new b.constructor();for
(let field in b){if(b.hasOwnProperty(field)){copy[field]=b[field];}}return copy;},F3=b=>{return b.$meta.item;};
function Bt(){P.call(this);this.dk=0;}
let Gq=(a,b)=>{a.dk=b;},C9=(a,b,c,d)=>{Bn(a,b,c,d);},D7=(a,b,c)=>{let d=new Bt();C9(d,a,b,c);return d;},FS=(a,b)=>{let c,d,e,f,g,h,i,j,k,l,m,n,o;c=Bb();d=a.cI;Y();e=d!==O?(-1):1;a:{f=a.cH+e|0;if(b.t(f,a.cG)&&b.u(f,a.cG)===null){c.v(I(f,a.cG));if(!(a.cI===O&&a.cH==1)){if(a.cI!==Be)break a;if(a.cH!=6)break a;}g=a.cH+(2*e|0)|0;if(b.t(g,a.cG)&&b.u(g,a.cG)===null)c.v(I(g,a.cG));}}h=BZ(2);i=h.data;i[0]=(-1);i[1]=1;j=i.length;k=0;while(k<j){l=i[k];m=a.cG+l|0;if(b.t(f,m)){n=b.u(f,m);if(n!==null&&n.w()!==a.cI)c.v(I(f,
m));else if(n===null){o=b.cf();if(o!==null&&o.bu(I(f,m)))c.v(I(f,m));}}k=k+1|0;}return c;},G1=a=>{Bc();return CB;};
function EE(){let a=this;D.call(a);a.cO=null;a.cP=null;}
let DL=a=>{K(a);a.cO=DK();Y();a.cP=O;},GF=()=>{let a=new EE();DL(a);return a;},E2=a=>{return a.cO;},FJ=a=>{return a.cP;},Fm=(a,b,c)=>{let d,e,f,g,h;d=a.cO.u(b.bc(),b.bd());if(d!==null&&d.w()===a.cP){e=d.E(a.cO);if(!e.G(c))return 0;f=a.cO.K();f.L(b,c);if(BP(f,a.cP))return 0;a.cO.L(b,c);if(d instanceof Bt){g=c.bc();h=a.cP;Y();!(h===O&&g==7)&&a.cP===Be&&g;}h=a.cP;Y();h=h!==O?O:Be;a.cP=h;return 1;}return 0;},FV=(a,b,c)=>{let d,e,f;a:{d=(a.cO.u(b.bc(),b.bd())).w();e=(-1);switch(c.bV()){case -2042963283:if(!c.bu(G(44)))break a;e
=2;break a;case 2553081:if(!c.bu(G(45)))break a;e=0;break a;case 1990023133:if(!c.bu(G(46)))break a;e=1;break a;default:}}b:{switch(e){case 0:f=Dt(d,b.bc(),b.bd());break b;case 1:f=D0(d,b.bc(),b.bd());break b;case 2:f=Eg(d,b.bc(),b.bd());break b;default:}f=Ed(d,b.bc(),b.bd());}a.cO.cg(b.bc(),b.bd(),f);},Gx=a=>{return GV(a.cO,a.cP);},FX=a=>{return Gs(a.cO,a.cP);};
function J(){D.call(this);this.cX=0;}
let EQ=null,FL=null,Fj=null,Bq=()=>{Bq=Bp(J);Hc();},DH=a=>{Bq();K(a);a.cL="";},HA=()=>{let a=new J();DH(a);return a;},D1=(a,b)=>{let c;Bq();c=b.data;K(a);a.cL=Eq(b.data,0,c.length);},E1=a=>{let b=new J();D1(b,a);return b;},El=(a,b)=>{a.cL=b;},E9=a=>{let b=new J();El(b,a);return b;},Ey=(a,b,c,d)=>{let e;Bq();e=b.data;K(a);GR(c,d,e.length);a.cL=Eq(b.data,c,d);},Gi=(a,b,c)=>{let d=new J();Ey(d,a,b,c);return d;},HD=(a,b)=>{if(b>=0&&b<a.cL.length)return a.cL.charCodeAt(b);S(D5());},GA=a=>{return a.cL.length;},Gc
=a=>{return a.cL.length?0:1;},FP=a=>{return a;},BJ=b=>{Bq();return b===null?G(30):b.f();},HM=(a,b)=>{let c;if(a===b)return 1;if(!(b instanceof J))return 0;c=b;return a.cL!==c.cL?0:1;},Hn=a=>{let b;a:{if(!a.cX){b=0;while(true){if(b>=a.cL.length)break a;a.cX=(31*a.cX|0)+a.cL.charCodeAt(b)|0;b=b+1|0;}}}return a.cX;},Hc=()=>{EQ=B0(0);FL=HA();Fj=E0();},EC=F(N),C6=a=>{Bl(a);},EN=()=>{let a=new EC();C6(a);return a;},GB=F();
function C4(){let a=this;D.call(a);a.cN=null;a.cT=null;}
let De=a=>{K(a);a.cN=Ev(P,[8,8]);GC(a);},DK=()=>{let a=new C4();De(a);return a;},GC=a=>{let b;Y();DV(a,0,O);DV(a,7,Be);b=0;while(b<8){a.cN.data[1].data[b]=D7(O,1,b);a.cN.data[6].data[b]=D7(Be,6,b);b=b+1|0;}},DV=(a,b,c)=>{let d;d=0;while(d<8){a.cN.data[b].data[d]=FD(a,c,b,d);d=d+1|0;}},FD=(a,b,c,d)=>{switch(d){case 0:case 7:return Dt(b,c,d);case 1:case 6:return Eg(b,c,d);case 2:case 5:return D0(b,c,d);case 3:return Ed(b,c,d);case 4:return Fx(b,c,d);default:}return null;},Ft=(a,b,c)=>{return b>=0&&b<8&&c>=0&&
c<8?1:0;},Gp=(a,b,c)=>{if(!a.t(b,c))return null;return a.cN.data[b].data[c];},Fr=(a,b,c,d)=>{if(a.t(b,c))a.cN.data[b].data[c]=d;},G4=a=>{return a.cT;},Hm=(a,b,c)=>{let d,e;d=a.u(b.bc(),b.bd());if(d===null)return;e=a.cT;a.cT=null;if(d instanceof Bt)G0(a,d,b,c,e);else if(d instanceof Bj&&BM(c.bd()-b.bd()|0)==2)EY(a,d,b,c);else Bo(a,d,b,c);},G0=(a,b,c,d,e)=>{let f,g,h,i,j;f=d.bc()-c.bc()|0;g=d.bd()-c.bd()|0;if(!g&&BM(f)==2){Bo(a,b,c,d);h=c.bc()+(f/2|0)|0;a.cT=I(h,c.bd());}else if(BM(g)==1&&BM(f)==1){if(a.u(d.bc(),
d.bd())===null&&e!==null&&e.bu(d)){i=b.w();Y();j=i!==O?d.bc()+1|0:d.bc()-1|0;a.cN.data[j].data[d.bd()]=null;}Bo(a,b,c,d);}else Bo(a,b,c,d);},EY=(a,b,c,d)=>{let e,f;Bo(a,b,c,d);e=c.bc();if(d.bd()<=c.bd()){f=a.u(e,0);Bo(a,f,I(e,0),I(e,d.bd()+1|0));}else{f=a.u(e,7);Bo(a,f,I(e,7),I(e,d.bd()-1|0));}},Bo=(a,b,c,d)=>{a.cN.data[d.bc()].data[d.bd()]=b;a.cN.data[c.bc()].data[c.bd()]=null;b.cH=d.bc();b.cG=d.bd();if(b instanceof BA)b.cr(1);if(b instanceof Bj)b.cs(1);if(b instanceof Bt)b.cr(1);},GO=(a,b)=>{let c,d,e;c=0;while
(c<8){d=0;while(d<8){e=a.u(c,d);if(e instanceof Bj&&e.w()===b)return I(c,d);d=d+1|0;}c=c+1|0;}return null;},Hv=(a,b)=>{let c,d,e,f;c=Bb();d=0;while(d<8){e=0;while(e<8){f=a.u(d,e);if(f!==null&&f.w()===b)c.v(f);e=e+1|0;}d=d+1|0;}return c;},EJ=(a,b,c,d)=>{let e,f,g;e=(a.z(d)).B();while(e.C()){f=e.D();g=!(f instanceof Bj)?f.E(a):f.F(a);if(g.G(I(b,c)))return 1;}return 0;},Fe=a=>{let b,c,d,e;b=DK();b.cN=Ev(P,[8,8]);c=0;while(c<8){d=0;while(d<8){e=a.u(c,d);if(e!==null)b.cN.data[c].data[d]=e.ct();d=d+1|0;}c=c+1|0;}b.cT
=a.cT;return b;},Et=F(0),DT=F(N),Ds=a=>{Bl(a);},BS=()=>{let a=new DT();Ds(a);return a;},Co=F(),Dp=a=>{K(a);},F7=()=>{let a=new Co();Dp(a);return a;},E8=(a,b)=>{Hr(b);},F5=(b,c)=>{c=Dj(c);b.cw(c);},C5=F(P),Ej=(a,b,c,d)=>{Bn(a,b,c,d);},Ed=(a,b,c)=>{let d=new C5();Ej(d,a,b,c);return d;},GE=(a,b)=>{let c,d,e,f,g,h,i,j,k,l;c=Bb();d=R(X(BG),8);e=d.data;e[0]=M([(-1),0]);e[1]=M([1,0]);e[2]=M([0,(-1)]);e[3]=M([0,1]);e[4]=M([(-1),(-1)]);e[5]=M([(-1),1]);e[6]=M([1,(-1)]);e[7]=M([1,1]);f=e.length;g=0;while(g<f){h=e[g];i
=h.data;j=a.cH+i[0]|0;k=a.cG+i[1]|0;a:{while(true){if(!b.t(j,k))break a;l=b.u(j,k);if(l!==null)break;c.v(I(j,k));j=j+i[0]|0;k=k+i[1]|0;}if(l.w()!==a.cI)c.v(I(j,k));}g=g+1|0;}return c;},FG=a=>{Bc();return Cq;},Cp=F(),Dk=a=>{K(a);},FU=()=>{let a=new Cp();Dk(a);return a;},Fa=(a,b)=>{GK(b);},Hy=(b,c)=>{c=Dj(c);b.cw(c);};
function Ep(){let a=this;D.call(a);a.c2=0;a.di=0;a.dc=0;a.de=0;a.cU=null;}
let Df=(a,b)=>{a.cU=b;K(a);a.di=a.cU.cS;a.dc=a.cU.cy();a.de=(-1);},Hl=a=>{let b=new Ep();Df(b,a);return b;},Gk=a=>{return a.c2>=a.dc?0:1;},GU=a=>{let b,c;GQ(a);a.de=a.c2;b=a.cU;c=a.c2;a.c2=c+1|0;return b.cA(c);},GQ=a=>{if(a.di>=a.cU.cS)return;S(Fz());};
function D$(){D.call(this);this.c7=null;}
let FQ=(a,b)=>{let c;K(a);a.c7=b;c=a;b.classObject=c;},Gj=a=>{let b=new D$();FQ(b,a);return b;},CI=b=>{let c;if(b===null)return null;c=b.classObject;if(c===null)c=Gj(b);return c;},CV=a=>{return a.c7;},Dh=a=>{return CI(F3(a.c7));},DE=F(0),DX=F(),C$=a=>{K(a);},E0=()=>{let a=new DX();C$(a);return a;};
Ge([]);
Dg([D,0,0,[],0,3,0,0,["m",E(CY),"bu",H(Fd),"f",E(DJ),"c",E(Dd),"q",E(Eo)],Bg,0,D,[],0,3,0,0,["h",E(FZ),"cD",E(Ex),"cE",E(EA)],Bk,0,Bg,[],0,3,0,0,["d",E(BU),"i",H(Ci)],N,0,Bk,[],0,3,0,0,["d",E(Bl),"i",H(B$)],BV,0,N,[],0,3,0,0,["d",E(Ct)],Cx,0,N,[],0,3,0,0,["i",H(B6)],HL,0,D,[],0,3,0,0,0,Gv,0,D,[],4,3,0,0,0,Bz,0,D,[],3,3,0,0,0,P,0,D,[Bz],1,3,0,0,["s",Ba(Bn),"w",E(G6),"J",E(FN),"ct",E(HG)],BA,0,P,[],0,3,0,0,["s",Ba(Er),"b9",E(Ho),"cr",H(FR),"E",H(Gb),"bf",E(HO)],E5,0,D,[],0,3,0,0,0,DS,0,D,[],3,3,0,0,0,B7,0,D,[DS],
3,3,0,0,0,B8,0,D,[B7],1,3,0,0,["d",E(EF),"G",H(Fy),"b6",H(EO)],Ee,0,D,[B7],3,3,0,0,0,DA,0,D,[Ee],3,3,0,0,0,Cb,0,B8,[DA],1,3,0,0,["d",E(Dv),"B",E(FA)],Bm,0,D,[],3,3,0,0,0,CD,0,D,[Bm],1,3,0,0,0,BD,0,D,[],3,3,0,0,0,Dx,0,CD,[BD],0,3,0,B3,0,Ca,0,Bk,[],0,3,0,0,["d",E(Du)],Di,0,N,[],0,3,0,0,["d",E(D2)],Br,0,D,[],3,3,0,0,0,Dq,0,D,[Br],3,3,0,0,0,Cz,0,D,[Dq],0,3,0,0,["d",E(CO),"Q",E(FH)],Cr,0,D,[BD],0,3,0,Cn,0,BH,0,D,[BD,Bm],1,3,0,0,["bN",L(CM),"f",E(Hx)],HF,0,D,[],4,3,0,0,0,EG,0,P,[],0,3,0,0,["s",Ba(D_),"E",H(Fn),"bf",
E(Gf)],DB,0,D,[],3,3,0,0,0,E6,0,D,[],4,3,0,0,0,HI,0,D,[],4,3,0,0,0,Eh,0,D,[],0,3,0,W,0,GW,0,D,[],4,3,0,0,0,Ch,0,D,[],3,3,0,0,0,DG,0,BV,[],0,3,0,0,["d",E(DQ)],BT,0,D,[Br],3,3,0,0,0,CA,0,D,[BT],0,3,0,0,["V",L(DP),"bt",H(EU),"br",H(Ec)],Gm,0,D,[],4,3,0,0,0,Fv,0,D,[Br],0,3,0,0,0,CW,0,D,[],3,3,0,0,0,BX,0,D,[CW,Bz],0,0,0,0,["bv",L(CJ)],Cs,0,BX,[],0,0,0,0,["b1",L(Dz)],C7,0,D,[],3,3,0,0,0,Ez,0,D,[],0,0,0,BB,0,BI,0,D,[Bm,Ch],0,0,0,0,["d",E(Ce),"bw",H(CC),"bI",H(Dn),"bE",L(CS),"bJ",H(DZ),"bC",L(DD),"bx",L(Dy),"bz",H(C2),
"f",E(DO)],ED,0,D,[],3,3,0,0,0,Dl,0,BI,[ED],0,3,0,0,["d",E(DI),"e",H(Bd),"bg",H(Cj),"bK",L(Gz),"bL",L(He),"bM",L(GN),"f",E(BC),"bz",H(G5),"bx",L(FM),"bC",L(EV),"bE",L(Hp)]]);
Dg([Ea,0,N,[],0,3,0,0,["d",E(Ef)],DR,0,D,[],3,3,0,0,0,C0,0,P,[],0,3,0,0,["s",Ba(D9),"E",H(E4),"bf",E(Hh)],CH,0,D,[Br],3,3,0,0,0,BN,0,BH,[],12,3,0,Y,0,BO,0,Bg,[],0,3,0,0,["r",L(Cm)],Cw,0,D,[DB],1,3,0,0,["d",E(CR)],BW,0,Cw,[Bz,Bm],0,3,0,0,["bR",H(Hk),"d",E(C3),"bw",H(B_),"bP",L(Ck),"bb",H(Hu),"bT",H(D6),"bW",Ba(Cv),"bU",E(CL),"Y",L(Gr),"b2",H(GP),"b0",E(GH)],BK,0,BH,[],12,3,0,Bc,0,C8,0,BO,[],0,3,0,0,["r",L(EB)],F6,0,N,[],0,3,0,0,0,CK,0,D,[],4,3,0,0,0,Bj,0,P,[],0,3,0,0,["s",Ba(Ek),"cs",H(Fi),"b_",H(HJ),"F",H(Gu),
"E",H(Hs),"bf",E(Gy)],Dc,0,D,[],3,3,0,0,0,B5,0,Cb,[Bz,Bm,Dc],0,3,0,0,["d",E(D3),"bw",H(Cf),"bz",H(GL),"cA",H(G2),"cy",E(EP),"v",H(EI),"bn",E(EW)],Cu,0,D,[],0,3,0,0,["p",L(Dm),"bc",E(Gn),"bd",E(GG),"bu",H(ES)],Cg,0,D,[BT],0,3,0,0,["d",E(CT),"bt",H(G7),"br",H(CP)],Cd,0,D,[BT],0,3,0,0,["d",E(DW),"bt",H(GY),"br",H(CX)],FO,0,D,[],4,3,0,0,0,Bt,0,P,[],0,3,0,0,["cr",H(Gq),"s",Ba(C9),"E",H(FS),"bf",E(G1)],EE,0,D,[],0,3,0,0,["d",E(DL),"be",E(E2),"bj",E(FJ),"bi",L(Fm),"bm",L(FV),"bo",E(Gx),"bp",E(FX)],J,0,D,[Bm,BD,Ch],
0,3,0,Bq,["d",E(DH),"T",H(D1),"cF",H(El),"bH",Ba(Ey),"bB",H(HD),"bA",E(GA),"by",E(Gc),"f",E(FP),"bu",H(HM),"bV",E(Hn)],EC,0,N,[],0,3,0,0,["d",E(C6)],GB,0,D,[Br],1,3,0,0,0,C4,0,D,[],0,3,0,0,["d",E(De),"t",L(Ft),"u",L(Gp),"cg",Ba(Fr),"cf",E(G4),"L",L(Hm),"x",H(GO),"z",H(Hv),"b$",Ba(EJ),"K",E(Fe)],Et,0,D,[],3,3,0,0,0,DT,0,N,[],0,3,0,0,["d",E(Ds)],Co,0,D,[CH],0,3,0,0,["d",E(Dp),"cw",H(E8)],C5,0,P,[],0,3,0,0,["s",Ba(Ej),"E",H(GE),"bf",E(FG)],Cp,0,D,[CH],0,3,0,0,["d",E(Dk),"cw",H(Fa)],Ep,0,D,[Et],0,0,0,0,["N",H(Df),
"C",E(Gk),"D",E(GU)],D$,0,D,[DR,C7],4,3,0,0,["o",E(CV),"l",E(Dh)],DE,0,D,[],3,3,0,0,0,DX,0,D,[DE],0,3,0,0,["d",E(C$)]]);
let FK=X(CQ),DM=X(BG);
FC(["<java_object>@","Clonage non supporté","Roi introuvable pour la couleur: ","0","board","images/board.png","WHITE_KING","images/king.png","BLACK_KING","images/king1.png","WHITE_QUEEN","images/queen.png","BLACK_QUEEN","images/queen1.png","WHITE_ROOK","images/rook.png","BLACK_ROOK","images/rook1.png","WHITE_BISHOP","images/bishop.png","BLACK_BISHOP","images/bishop1.png","WHITE_KNIGHT","images/knight.png","BLACK_KNIGHT","images/knight1.png","WHITE_PAWN","images/pawn.png","BLACK_PAWN","images/pawn1.png","null",
"WHITE","BLACK","KING","QUEEN","ROOK","BISHOP","KNIGHT","PAWN","object","function","string","number","undefined","Knight","Rook","Bishop"]);
J.prototype.toString=function(){return CG(this);};
J.prototype.valueOf=J.prototype.toString;D.prototype.toString=function(){return CG(DJ(this));};
D.prototype.__teavm_class__=function(){return Hq(this);};
let C=EK(Fb);
C.javaException=ET;
let H0=Symbol('jsoClass');
(()=>{let c;c=Cz.prototype;c.onTimer=Bv(Gl);c=CA.prototype;c.handleEvent=Bv(F1);c=Cg.prototype;c.handleEvent=Bv(F4);c=Cd.prototype;c.handleEvent=Bv(Gt);c=Co.prototype;c.accept=Bv(F5);c=Cp.prototype;c.accept=Bv(Hy);})();
B.main=C;}));
